# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RinexImporter
                                 A QGIS plugin
 Importer des fichiers RINEX et afficher leurs points GNSS dans QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-23
        copyright            : (C) 2025 by khalid.lahjouji
        email                : khalid.lahjouji@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RinexImporter class from file RinexImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rinex_importer import RinexImporter
    return RinexImporter(iface)